"""Update Category Table

Revision ID: 650bbb4a4003
Revises: b7d65077cbf6
Create Date: 2018-10-20 23:44:14.094323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650bbb4a4003'
down_revision = 'b7d65077cbf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'shortDescription')
    op.drop_column('category', 'Details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('Details', sa.VARCHAR(length=256), nullable=True))
    op.add_column('category', sa.Column('shortDescription', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
